---
abstract: "L<Padre> and JavaScript\r"
author:
  - 'Gabor Szabo'
build_requires:
  Test::More: 0.47
  Test::NeedsDisplay: 1.05
  Test::NoWarnings: 0.084
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-JavaScript
no_index:
  directory:
    -
      - t
      - xt
      - eg
      - share
      - inc
      - privinc
    - inc
    - t
requires:
  Class::Autouse: 1.26
  Exporter: 0
  JavaScript::Beautifier: 0.03
  JavaScript::Minifier::XS: 0
  Padre: 0.21
  perl: 5.008001
resources:
  bugtracker: http://padre.perlide.org/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-JavaScript
version: 0.23
